
package id.co.id.indocyber.guessgame;

import id.co.id.indocyber.guessgame.model.WordModel;
import id.co.id.indocyber.guessgame.model.WordQuestionGenerator;
import java.io.IOException;
import java.util.List;
import java.util.Arrays;
import java.util.Collection;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Collation;

/**
 *
 * @author Misbahul Munir
 */
public class GuessingGame extends javax.swing.JFrame {

    WordModel basicWord;

//WordModel soal1=new WordModel("Pondok indah","Daerah Dijakarta Selatan");
//WordModel soal2=new WordModel("Sudirman","Jalan Utama di Jakarta");
//WordModel soal3=new WordModel("Tugu Tani","Patung Deket Monas");
//WordModel soal4=new WordModel("Citos","Mall Dijakarta Selatan");
//WordModel soal5=new WordModel("Gandaria City","Mall Anak Muda");
//WordModel [] bankSoal={soal1,soal2,soal3,soal4,soal5};
    List<WordModel> bankSoal;
    private String kata;

    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() throws IOException {
        bankSoal = WordQuestionGenerator.createQuestionFromFile("C:\\JAVA_LATIHAN\\io.txt");
        initComponents();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
        tanggalSekarang();

    }

    private void tanggalSekarang() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat formatTanggal = new java.text.SimpleDateFormat("EEEEE, dd MMMMM yyyy");
        tanggalLabel.setText(formatTanggal.format(sekarang));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        checkAnswerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tanggalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guessing Game");

        soalTextField.setEnabled(false);

        checkAnswerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/id/indocyber/gambar/Preview_16x16.png"))); // NOI18N
        checkAnswerButton.setText("Proses");
        checkAnswerButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/id/indocyber/gambar/Check_16x16.png"))); // NOI18N
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban");

        commentLabel.setText("Keterangan");

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/id/indocyber/gambar/Preview_16x16.png"))); // NOI18N
        startButton.setText("Mulai");
        startButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/id/indocyber/gambar/Check_16x16.png"))); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("Hint");

        jLabel2.setText("Clue :");

        tanggalLabel.setText("Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(soalTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkAnswerButton)
                                    .addComponent(jLabel1)
                                    .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 63, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAnswerButton)
                .addGap(18, 18, 18)
                .addComponent(commentLabel)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
//        int soalIndex=(int)Math.floor(Math.random()*bankSoal.length);
//        System.out.println("indeks "+soalIndex);
//        basicWord=bankSoal[soalIndex];      
//        System.out.println(basicWord.getBasicWord());
//        soalTextField.setText(basicWord.createSoal());
//        hintLabel.setText(basicWord.getHint());

        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size());
        System.out.println("indeks " + soalIndex);
        basicWord = bankSoal.get(soalIndex);
        System.out.println(basicWord.getBasicWord());
        soalTextField.setText(basicWord.acakHuruf());
        hintLabel.setText(basicWord.getHint());

    }//GEN-LAST:event_startButtonActionPerformed

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
        // TODO add your handling code here:
        int jumlah=basicWord.getJumlahTebakan()+1;
        String jawaban = jawabanTextField.getText().trim();
        basicWord.setJawaban(jawaban);
        if (basicWord.cekJawaban()) {
            commentLabel.setText("Anda Benar, Anda Telah Menebak Sebanyak "+jumlah);
        } else {
            commentLabel.setText("Coba Lagi");
            commentLabel.getToolkit().beep();
            jawabanTextField.setText("");
            jawabanTextField.requestFocus();
        }
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuessingGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuessingGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JTextField soalTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel tanggalLabel;
    // End of variables declaration//GEN-END:variables
}
